version: "3.3"

services:
  database:
    image: mongo:3.2.21

  api:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
     - database
    environment:
      spring.data.mongodb.host: database
